### ISSUE TITLE
Return null

### ISSUE THREAD

**Issue by emresaracoglu** [rinvex/universities#12]
Hello 

Thank you for this project.

I just want to print the universities in Turkey but coming up empty.

         include "vendor/autoload.php";  

	$Universities = universities('tr');
	 
	 print_r($Universities);
	
What is the problem?
Thank yo again

**Comment by ScSherifTarek** [comment]
Hello @emresaracoglu 
I think that because the names.json file didn't change to use the countries code the country name will do the work for now. you can use this `universities('turkey')`

**Comment by ScSherifTarek** [comment]
You can use [Locale](https://www.php.net/manual/en/class.locale.php) class to get the country name then pass the country name instead of the country code that works for most of the countries but countries like "Côte d'Ivoire" are named here in English so this solution will not work for all the countries but it can for some.
I think a file maps between the country code and its name here will do the work.
\Locale::getDisplayRegion('-'.$countryCode, 'en')

**Comment by Omranic** [comment]
Thank you @ScSherifTarek for pointing the correct answer for the current release.

@emresaracoglu  In the future I'm planning to change the behavior of this package to use country ISO codes, PRs are welcome :)
